# Generated by Django 5.2.10 on 2026-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
