# Generated by Django 4.2 on 2026-01-29 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0002_projectstatus_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstatus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='project_id',
            field=models.CharField(default='project_1', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
